### 分页查询
POST {{content_host}}/content/course/list?pageNo=1&pageSize=6
Content-Type: application/json

{
  "courseName": "spring"
}

<> 2023-04-18T190955.200.json

### 请求体得换行才可以

### 课程类别信息
GET {{content_host}}/content/course-category/tree-nodes/

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 11,
  "originalPrice":22,
  "qq": "33",
  "wechat": "44",
  "phone": "55",
  "validDays": 66,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "python入门",
  "teachmode": "200002",
  "users": "python入门python入门python入门",
  "tags": "",
  "grade": "204001",
  "description": "python入门python入门python入门python入门python入门"
}