###
POST {{content_host}}/content/course/list?pageNo=1&pageSize=6
Content-Type: application/json

{
  "courseName": "spring"
}

<> 2023-04-18T190955.200.json

### 请求体得换行才可以

###
#GET http://localhost:63040/content/test

GET {{content_host}}/content/course-category/tree-nodes/