### 分页查询
POST {{content_host}}/content/course/list?pageNo=1&pageSize=6
Content-Type: application/json

{
  "courseName": "spring"
}

<> 2023-04-18T190955.200.json

### 请求体得换行才可以

### 课程类别信息
GET {{content_host}}/content/course-category/tree-nodes/

### 新增课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 11,
  "originalPrice": 22,
  "qq": "33",
  "wechat": "44",
  "phone": "55",
  "validDays": 66,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "python入门",
  "teachmode": "200002",
  "users": "python入门python入门python入门",
  "tags": "",
  "grade": "204001",
  "description": "python入门p"
}


### 根据 id 查询课程基本信息
GET {{content_host}}/content/course/2

### 根据 id 修改课程基本信息
PUT {{content_host}}/content/course/
Content-Type: application/json

{
  "id": 2,
  "companyId": 1232141425,
  "companyName": "Test1",
  "name": "测试课程0-1",
  "users": "121312121212121212",
  "tags": "课程标签",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "teachmode": "200002",
  "description": "这是个测试课程这是个测试课程这是个测试课程121",
  "pic": "/mediafiles/2022/09/18/a16da7a132559daf9e1193166b3e7f52.jpg",
  "createDate": "2019-09-04 08:49:26",
  "changeDate": "2022-09-18 15:01:47",
  "createPeople": null,
  "changePeople": null,
  "auditStatus": "202004",
  "status": "203002",
  "charge": "201001",
  "price": 1.0,
  "originalPrice": 11111.0,
  "qq": "2222",
  "wechat": "3333",
  "phone": "4444",
  "validDays": 555,
  "mtName": "前端开发",
  "stName": "HTML/CSS"
}

### 查询某个课程的课程计划
GET http://localhost:63040/content/teachplan/117/tree-nodes


### 新增课程计划--章
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId": 74,
  "parentid": 0,
  "grade": 1,
  "pname": "新章74名称 [点击修改1]"
}

### 新增课程计划--节,从数据库找到第一级的课程计划id向其下边添加计划
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId": 74,
  "parentid": 247,
  "grade": 2,
  "pname": "小节名称74 [点击修改1]"
}

### 课程课程计划,需要从数据库找到修改的课程计划id
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "changeDate": null,
  "courseId": 22,
  "cousePubId": null,
  "createDate": null,
  "ctlBarShow": false,
  "ctlEditTitle": true,
  "endTime": null,
  "grade": "2",
  "isPreview": "1",
  "mediaType": "",
  "orderby": 1,
  "parentid": 237,
  "pname": "第1节修改名称2",
  "startTime": null,
  "status": null,
  "teachPlanId": 240
}


### 根据teachplan id 删除章
DELETE http://localhost:63040/content/teachplan/293

### 根据课程id查询该课程的所有老师信息
http://localhost:63040/content/courseTeacher/list/22

### 课程查询列表
POST {{gateway_host}}/content/course/list?pageNo=2&pageSize=1
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": ""
}


