### 媒资管理-上传文件
### 上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="rbrb.jpeg"
Content-Type: application/octet-stream

< d:/rbrb.jpeg